tweet:
  url: 'https://suitcase-rabbits.com/'
  related: 'suitcaserabbits'
  hashtags: 'スーツケースのうさぎたち'
marker_size:
  width: 20
  height: 30
vertial_space:
  - left: 507
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: A
    num: 1
    reverse: true
  - left: 600
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: A
    num: 11
    reverse: true
  - left: 725
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: B
    num: 1
    reverse: true
  - left: 818
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: B
    num: 11
    reverse: true
  - left: 952
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: C
    num: 1
    reverse: true
  - left: 1045
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: C
    num: 11
    reverse: true
  - left: 1178
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: D
    num: 1
    reverse: true
  - left: 1271
    tops:
      - '216'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: D
    num: 11
    reverse: true
  - left: 1392
    tops:
      - '180'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: E
    num: 9
    reverse: true
  - left: 1392
    tops:
      - '531'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
      - '+3'
      - '+2'
    sym: E
    num: 1
    reverse: true



